### PR TITLE
fix: `arcas` hangs for >2m when Avi not reachable

### PR DESCRIPTION
**Pull request by carlosonunez-vmw**
If an Avi node is not reachable at port 443, `arcas` will hang "waiting"
for it to come up. This fix front-loads this by making sure the IP
address we're hitting is serving HTTPS.

Signed-off-by: Carlos Nunez <ncarlos@vmware.com>

### CODE REVIEW

**Comment by rashikwal** [comment]
Hi @carlosonunez-vmw, I was testing out this code on a lab where AVI is already up deployed and there the check was failing so I am not adding it to the code base, I'll check on the reason for failure and will update it with your changes.

**Comment by carlosonunez-vmw** [comment]
@rashikwal I think I found some of the stumbling blocks you ran into. Can you give this another look?

**Comment by rashikwal** [comment]
Hi @carlosonunez-vmw, I'll test out the changes and will update you on it.

**Comment by sunshetty** [comment]
@carlosonunez-vmw Can you update the PR and raise it against the newly released version 1.3-1.5.4?

**Pull request closed without merging**
